# Generated by Django 3.2.8 on 2021-12-22 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20211222_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 22, 21, 24, 15, 231073)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
