# Generated by Django 3.2.8 on 2021-12-22 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20211222_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_url',
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.CharField(default='https://cdn.dribbble.com/users/72948/screenshots/1631127/cell311.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 22, 21, 30, 1, 355145)),
        ),
    ]
